name: Rspec Test Fulltrack

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    strategy:
      matrix:
        ruby-version: ["3.4.2"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec --format documentation
      - name: Build YARD docs
        run: bundle exec yard doc --output-dir yard_output
      - name: Pages artifact prep
        run: |
          mkdir -p public/coverage
          mkdir -p public/doc
          mv coverage/* public/coverage/
          mv yard_output/* public/doc/
          touch public/.nojekyll
      - name: Deploy coverage to Github page
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - uses: actions/deploy-pages@v4
